// <auto-generated />
using System;
using IqTest_server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IqTest_server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250516000000_AddTimeAndIQFields")]
    partial class AddTimeAndIQFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            // This is a partial designer file just for the migration
            // The full model would be built here
#pragma warning restore 612, 618
        }
    }
}